# Copyright 2019 VMware, all rights reserved.
# This software is released under MIT license.
# The full license information can be found in LICENSE in the root directory of this project.

sudo: true

addons:
  chrome: stable

language: node_js

node_js:
  - "10.17.0"
services:
  - docker
  - xvfb
before_install:
- cd supply-chain
- npm install
- docker-compose build
- npm install -g ganache-cli
- npm install -g truffle@4.1.15
- export DISPLAY=:99.0
- cd ..

script:
- cd supply-chain
- ganache-cli -p 7545 --networkId 5777 > /dev/null &
- truffle migrate --reset
- npm run start:ganache > /dev/null &
- sleep 25
- npm run lint
- npm run test:travis
- npm run truffle:test:ganache
