apiVersion: v1
kind: ConfigMap
metadata:
  name: vmbc-configmap-client-1-clientservice
binaryData:
  # client service config file
  {{- $clientserviceconfigfile := "client-1/config/clientservice/clientservice.config" }}
  clientservice-config-file: {{ $.Files.Get $clientserviceconfigfile | b64enc }}
  # environment vars file
  {{- $environmentvarsfile := "client-1/config/clientservice/environment-vars" }}
  environment-vars-file: {{ $.Files.Get $environmentvarsfile | b64enc }}