apiVersion: v1
kind: ConfigMap
metadata:
  name: vmbc-configmap-replica-3-concord
  labels:
    blockchainId: {{ .Values.global.blockchainId }}
binaryData:
  # deployment config file
  # Parameterize deployment.config file from Values if needed:
  # - convert config file to dict
  # - replace values from Values.yaml
  {{- $depconfigfile := "replica-3/config/concord/config-local/deployment.config" }}
  {{- $deploymentDict := $.Files.Get $depconfigfile | fromYaml }}
  {{- $_ := set $deploymentDict "eth_permissioning_write_enabled" .Values.permissioning.ethPermissioningWriteEnabled }}
  {{- $_ := set $deploymentDict "utt_enabled" .Values.privacy.privacyEnabled }}
  {{ if .Values.privacy.privacyEnabled }}
  {{- $_ := set $deploymentDict "consensus_batching_policy" 2 }}
  {{ end }}
  # Set up overridable replica checkpoint properties
  {{- $_ := set $deploymentDict "FEATURE_db_checkpoints" .Values.replicaCheckpointBackup.enabled }}
  {{- $_ := set $deploymentDict "num_of_rocksdbcheckpoints" .Values.replicaCheckpointBackup.numberOfCheckpoints }}
  {{- $_ := set $deploymentDict "db_checkpoint_duration" .Values.replicaCheckpointBackup.checkpointIntervalInSeconds }}
  {{- $_ := set $deploymentDict "dbcheckpoint_window" .Values.replicaCheckpointBackup.checkpointWindow }}
  deployment-config-file: {{ $deploymentDict | toYaml | b64enc }}
  # secrets config file
  {{- $secretsconfigfile := "replica-3/config/concord/config-local/secrets.config" }}
  secrets-config-file: {{ $.Files.Get $secretsconfigfile | b64enc }}
  # application config file
  {{- $applicationconfigfile := "replica-3/config/concord/config-local/application.config" }}
  application-config-file: {{ $.Files.Get $applicationconfigfile | b64enc }}

