## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets [array] Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  # Used to isolate different deployments
  blockchainId: "746d220e-1eb9-4d15-ae1b-a224cee8d396"
  sessionIdentifier: "069a1cd4-0fdf-4f5d-9109-982e6b618f87"
  # The credentials for the docker registry. If username/password/email are specified, a corresponding Secret
  # with the name vmwathena-regcred is created.
  imageCredentials:
    registry: ""
    username: |-
      
    password: |-
      
    email: ""
  storageClassName: "standard"

  # The global artifact tag
  image:
    tag: "0.0.0.0.7849"

## @section replica-specific GLOBAL parameters (applies to all replicas)
##
concord:
  image:
    repository: "vmwblockchain/concord-core"
    tag: ""

## @section clientservice-specific GLOBAL parameters
##
clientservice:
  image:
    repository: "vmwblockchain/clientservice"
    tag: ""

## @section ethrpc-specific GLOBAL parameters
##
ethrpc:
  image:
    repository: "vmwblockchain/ethrpc"
    tag: ""

## @section fluentd-specific parameters
fluentd:
  image:
    repository: "vmwblockchain/fluentd"
    tag: 1.2

## @section logmanagement-specific parameters
## In format ${i} vaies from 1 to n
## logManagement
##   endpoint_${i}:
##      url: "";
##      userName: ""
##      password: ""
logManagement: 
  endpoint_1:
    url: "http://logstash-logstash.default.svc.cluster.local:8080"
    username: ""
    password: ""


resources:
  replica:
    defaultCpuRequest: 100m
    cpuRequest: "100m"
    defaultCpuLimit: 100m
    cpuLimit: "100m"
    defaultMemoryRequest: 1225Mi
    memoryRequest: "2000Mi"
    defaultMemoryLimit: 1225Mi
    memoryLimit: "2000Mi"
    defaultStorageRequest: 1Gi
    storageRequest: "8Gi"
  client:
    defaultCpuRequest: 100m
    cpuRequest: "100m"
    defaultCpuLimit: 100m
    cpuLimit: "100m"
    defaultMemoryRequest: 500Mi
    memoryRequest: "500Mi"
    defaultMemoryLimit: 500Mi
    memoryLimit: "500Mi"

## External Names


## Storage class Names
storageClassNames:
  replica:
    replica1: standard
    replica0: standard
    replica3: standard
    replica2: standard


serviceAccount:
  ## @param serviceAccount.create Enable/disable service account creation
  ##
  create: false
  ## @param serviceAccount.name Name of the service account to create or use
  ##
  name: ""
  ## @param serviceAccount.automountServiceAccountToken Enable/disable auto mounting of service account token
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
  ##
  automountServiceAccountToken: true
  ## @param serviceAccount.annotations [object] Additional annotations to be included on the service account
  ##
  annotations: {}
  ## @param serviceAccount.labels [object] Additional labels to be included on the service account
  ##
  labels: {}

genesisBlock:
    ## @param genesisBlock.config Configurations for genesis block
    ##
    config:
      ## @param genesisBlock.config.chainId Chain id for genesis block
      ##
      chainId: 5000

    ## @param genesisBlock.alloc List of accounts
    ##
    alloc: [fb389874fb4e03182a7358275eaf78008775c7ed]
    ## @param genesisBlock.permissioningContractAddress Contract address for permissioning
    ##
    permissioningContractAddress: "0x57a268e7694371880a2c5881bd240db812bbfbf0"
    ## @param genesisBlock.permissioningContractBin Contract bin for permissioning
    ##
    permissioningContractBin: "6080604052600080553480156200001557600080fd5b5060405162000b8238038062000b8283398181016040528101906200003b919062000322565b600081511162000082576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016200007990620003fa565b60405180910390fd5b60005b81518110156200012457600460026001600817171760016000848481518110620000b457620000b36200041c565b5b602002602001015173ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff021916908360ff16021790555080806200011b9062000484565b91505062000085565b50805160008190555050620004d1565b6000604051905090565b600080fd5b600080fd5b600080fd5b6000601f19601f8301169050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b62000198826200014d565b810181811067ffffffffffffffff82111715620001ba57620001b96200015e565b5b80604052505050565b6000620001cf62000134565b9050620001dd82826200018d565b919050565b600067ffffffffffffffff8211156200020057620001ff6200015e565b5b602082029050602081019050919050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000620002438262000216565b9050919050565b620002558162000236565b81146200026157600080fd5b50565b60008151905062000275816200024a565b92915050565b6000620002926200028c84620001e2565b620001c3565b90508083825260208201905060208402830185811115620002b857620002b762000211565b5b835b81811015620002e55780620002d0888262000264565b845260208401935050602081019050620002ba565b5050509392505050565b600082601f83011262000307576200030662000148565b5b8151620003198482602086016200027b565b91505092915050565b6000602082840312156200033b576200033a6200013e565b5b600082015167ffffffffffffffff8111156200035c576200035b62000143565b5b6200036a84828501620002ef565b91505092915050565b600082825260208201905092915050565b7f4174206c65617374206f6e652061646d696e206164647265737320726571756960008201527f7265640000000000000000000000000000000000000000000000000000000000602082015250565b6000620003e260238362000373565b9150620003ef8262000384565b604082019050919050565b600060208201905081810360008301526200041581620003d3565b9050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b6000819050919050565b600062000491826200047a565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8203620004c657620004c56200044b565b5b600182019050919050565b6106a180620004e16000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80630c022bbe1461003b5780638f907af014610057575b600080fd5b61005560048036038101906100509190610565565b610087565b005b610071600480360381019061006c9190610565565b61035e565b60405161007e91906105d3565b60405180910390f35b6100943360006008610374565b6100d3576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100ca9061064b565b60405180910390fd5b60008160ff1603610141578060ff168273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167fc7262695771bdf4ea9c25885b800c0bc8d018ca37f04b26442c28d6214ea93a160405160405180910390a46101a0565b8060ff168273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167f1b8547495b9b7c7e5fc976f16a2adff97eb2f0bf7e8380e7de2bc79f3fde0ec960405160405180910390a45b600073ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff16036102315780600260008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff021916908360ff160217905550610359565b600073ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16036102c25780600160008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff021916908360ff160217905550610358565b80600360008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff021916908360ff1602179055505b5b505050565b600061036b848484610374565b90509392505050565b600080600160008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff1660ff1690506000600260008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff1660ff1690506000600360008873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008773ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff1660ff1690508460ff168560ff168284861717161493505050509392505050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006104f9826104ce565b9050919050565b610509816104ee565b811461051457600080fd5b50565b60008135905061052681610500565b92915050565b600060ff82169050919050565b6105428161052c565b811461054d57600080fd5b50565b60008135905061055f81610539565b92915050565b60008060006060848603121561057e5761057d6104c9565b5b600061058c86828701610517565b935050602061059d86828701610517565b92505060406105ae86828701610550565b9150509250925092565b60008115159050919050565b6105cd816105b8565b82525050565b60006020820190506105e860008301846105c4565b92915050565b600082825260208201905092915050565b7f4e6f7420616e2041646d696e0000000000000000000000000000000000000000600082015250565b6000610635600c836105ee565b9150610640826105ff565b602082019050919050565b6000602082019050818103600083015261066481610628565b905091905056fea2646970667358221220370e2f95d17db66d19fd6fbb067c54c2ee8e8bdb65c12a5b99536ec21114fe0b64736f6c634300080d0033"
    ## @param genesisBlock.uttVirtualContractAddress Contract address for UTT privacy virtual contract
permissioning:
  ## @param permissioning.ethPermissioningWriteEnabled Eth permissioning write enabled flag
  ##
  ethPermissioningWriteEnabled: false
  ## @param permissioning.ethPermissioningReadEnabled Eth permissioning read enabled flag
  ##
  ethPermissioningReadEnabled: false
